### ISSUE TITLE
Support for open source models

### ISSUE THREAD

**Issue by bhupesh-sf** [patched-codes/patchwork#414]
First of all thanks for this quite wonderful project. This is really containing certain good workflows which we deal day to day.

Just a question will we be able to use open source models? They can be openAI API compatible.

**Comment by codelion** [comment]
Yes you can use open-source models. I will update the README and docs to make it more clear. But there are two ways to configure patchwork. First is via the CLI, so you can change the `client_base_url` to  any OpenAI compatible endpoint.

E.g. to use Llama 3.1 405B from Groq.com you can use:

```
patchwork AutoFix client_base_url=https://api.groq.com/openai/v1 openai_api_key=your_groq_key model=llama-3.1-405b-reasoning
```

You can also use a  config file to do the same, e.g. if you want to use Llama 3.1 405B from Hugging Face you can create a config.yml file:

```yaml
openai_api_key: your_hf_token
client_base_url: https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-405B-Instruct-FP8/v1
model: Meta-Llama-3.1-405B-Instruct-FP8
```

And run as:

```
patchwork AutoFix --config=/path/to/config.yml
```
